# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false

  comments:
    min-spaces-from-content: 1

  indentation:
    spaces: 2
    indent-sequences: true

  document-start: disable

  braces:
    max-spaces-inside: 1

  brackets:
    max-spaces-inside: 1

ignore: |
  .terraform/
