name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - hatamiarash7

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened...
    validations:
      required: true

  - type: textarea
    id: terraform-config
    attributes:
      label: Terraform Configuration
      description: |
        Please provide the relevant Terraform configuration.
        Make sure to remove any sensitive information (API keys, passwords, etc.)
      render: hcl
      placeholder: |
        module "cdn_dns" {
          source = "..."
          # your configuration here
        }
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Please paste the error output from Terraform.
      render: shell
      placeholder: |
        Error: ...
    validations:
      required: false

  - type: input
    id: terraform-version
    attributes:
      label: Terraform Version
      description: Output of `terraform version`
      placeholder: "v1.5.0"
    validations:
      required: true

  - type: input
    id: provider-version
    attributes:
      label: ArvanCloud Provider Version
      description: Version of the ArvanCloud Terraform provider
      placeholder: "0.2.2"
    validations:
      required: true

  - type: input
    id: module-version
    attributes:
      label: Module Version
      description: Version of this module you're using
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information...
    validations:
      required: false
